### ISSUE TITLE
ES5/类型 => 5.Number 类型 翻译小错误。

### ISSUE THREAD

**Issue by ty96** [w3c-html-ig-zh/es5#1]
ES5/类型 => 5.Number 类型

第一个代码框下方

这里的 s 是 +1 或 -1，m 是一个小于 253 但不小于 252 的正整数，~~m 是一个~~ 闭区间 -1074 到 971 中的整数。

应纠正为：

这里的 s 是 +1 或 -1，m 是一个小于 253 但不小于 252 的正整数，e 是一个 闭区间 -1074 到 971 中的整数。

**Comment by zqzhang** [comment]
非常感谢，@Toxni

欢迎参与该项目。
